# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ END4 DOTFILES PERSISTENT OVERRIDES (TRUE AMOLED & 180HZ LOCK)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# 1. Mengunci Dekorasi Screen Shader AMOLED (Formula Intel/NVIDIA Universal)
decoration {
    screen_shader = /home/alimzicus/.config/hypr/shaders/amoled.frag
    rounding = 14
    rounding_power = 3.0
}

